fleemarket/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sells
end

fleemarket/app/models/sell.rb
class Sell < ApplicationRecord
end

fleemarket/app/controllers/sells_controller.rb
class SellsController < ApplicationController
	def index
		@sells = Sell.all
	end
	def show
    @sell = Sell.find(params[:id])
  end

	def new
	end

	def create
  	@sell = Sell.new(params.require(:sell).permit(:product, :description))
 
  	@sell.save
  	redirect_to @sell
	end

	private
		def sell_params
    	params.require(:sell).permit(:product, :description)
		end
end

fleemarket/app/helpers/sells_helper.rb
module SellsHelper
end

fleemarket/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fleemarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fleemarket/app/views/sells/index.html.erb
<h1>Listing products</h1>
<%= link_to 'New product', new_sell_path %> 
<table>
  <tr>
    <th>Product</th>
    <th>Description</th>
  </tr>
 
  <% @sells.each do |sell| %>
    <tr>
      <td><%= sell.product %></td>
      <td><%= sell.description %></td>
      <td><%= link_to 'Show', sell_path(sell) %></td>
    </tr>
  <% end %>
</table>

fleemarket/app/views/sells/new.html.erb
<h1>New Product</h1>

<%= form_for :sell, url: sells_path do |f| %>
  <p>
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', sells_path %>

fleemarket/app/views/sells/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @sell.product %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @sell.description %>
</p>

<%= link_to 'Back', sells_path %>